### ISSUE TITLE
[Furnus using limelib-1.12-1.7.6] Shift-clicking for removal does not produce XP

### ISSUE THREAD

**Issue by zontargs** [KidsDontPlay/LimeLib#11]
[Referencing https://github.com/MrRiegel/Furnus/issues/27]

When using shift-click (vanilla's fast-move to inventory function) to remove products from the Furnus or Pulvus, no experience is produced. Click-and-drag removal works just fine.

**Comment by KidsDontPlay** [comment]
I made a mistake and I don't know why.
Fixed in next limelib version
