### ISSUE TITLE
1.12(java.lang.NullPointerException: Unexpected error)

### ISSUE THREAD

**Issue by SDUBZ** [KidsDontPlay/LimeLib#12]
Forge:1.12-2443
Limelib: 1.12-1.7.5

crash when exploring village

crash report:
[crash-2017-08-12_21.27.16-client.txt](https://github.com/MrRiegel/LimeLib/files/1219718/crash-2017-08-12_21.27.16-client.txt)

**Comment by KidsDontPlay** [comment]
Use latest version
