### ISSUE TITLE
[1.12] - Game crash when placing Compact Machine 3

### ISSUE THREAD

**Issue by Protheus** [KidsDontPlay/LimeLib#13]
**MC**: 1.12
**Forge**: 2443

**Limelib**: limelib-1.12-1.7.7
**CM3**: compactmachines3-1.12.1-3.0.0-b119

**Pastebin**: https://pastebin.com/F7jxrKGQ

**Issue:** 
When CM3 and Limelib are installed and you place a CM3, the game gives the crash stated in the pastebin.

**Reproduce:**

- Install both CM3 and Limelib
- Create new world
- place a CM3 block
- Game crash

In limelib config changed the default **TRUE** to **FALSE** and still game crash

**Config:**

    # Command blocks are available in redstone creative tab. [default: true]
    B:commandBlockCreativeTab=true

    #  [default: true]
    B:energyConfigHint=false

    #  [default: true]
    B:showEnergy=false

**Comment by KidsDontPlay** [comment]
It's CM3's fault.
@thraaawn
`getCapability()` shouldn't return `null` when `hasCapability()` returns `true`.

**Comment by Protheus** [comment]
Can close. Will create an issue with cm3. Thank you

**Comment by davenonymous** [comment]
Thanks for catching that. Fixed. Build is uploaded to curse and waiting for approval. Cheers!
