### ISSUE TITLE
Limelib + TATW + placing IC2 machines = crash

### ISSUE THREAD

**Issue by Staegrin** [KidsDontPlay/LimeLib#15]
Working on a 1.12.2 modpack. Found a problem when placing IC2 machines

Narrowed it down to limelib and the mod TATW from aroma1997 conflicting. Turning either off will prevent problems. Sadly TATW is the only mod by aroma that doesn't have an Issues page so I can't notify them.

So no problems until you try to place an IC2 machine (block that produces or uses EU power). Placing = instant crash.

IC2 blocks that aren't machines cause no problems.

Installed:
Minecraft version 1.12.2
Forge: 14.23.0.2531
Mods;
Aroma1997core
BrandonsCore
Codechickenlib
draconicevolution
industrialcraft vesion industrialcraft-2-2.8.16-ex112
JEI
limelib version limelib-1.12.2-1.7.9
redstoneFlux version RedstoneFlux-1.12-2.0.1.2-universal
TATW version Tatw-1.12.2-1.0.1.2

crashlog:
https://gist.github.com/Staegrin/2813c3a03ead9f16348a0da36664eb92

full log:
https://gist.github.com/Staegrin/e7898c7e451c15fc202328fa6fc8ec82

TATW curseforge page
https://minecraft.curseforge.com/projects/tatw?gameCategorySlug=mc-mods&projectID=263980

**Comment by KidsDontPlay** [comment]
I guess it's up to Aroma to fix this

**Comment by Aroma1997** [comment]
Should be fixed in build 19: https://ci.aroma1997.org/job/TATW/
