### ISSUE TITLE
limelib + mekanism + modular machinery (fluid output/input)= crash

### ISSUE THREAD

**Issue by Staegrin** [KidsDontPlay/LimeLib#16]
Interesting crash
Minecraft version 1.12.2 forge 14.23.0.2537
3 mods loaded (not counting JEI)
mekanism latest version 1.9.4.1.326
modular machinery 1.6.5 (https://minecraft.curseforge.com/projects/modular-machinery)
limelib 1.12.2-1.7.9

If either one of the three mods are disabled the crash doesn't happen. The crash happens when a fluid output/input from modular machinery is placed in world and limelib tries to read the block's info. I think it has something to do with the fact that it handles Mekanism gasses also when that mod is active.

crashlog: https://gist.github.com/Staegrin/cf967391278c9912f08c5ab466391f55
crashlog client: https://gist.github.com/Staegrin/5f86b54f02a54e4642da31aabb8ee18f
crashlog server: https://gist.github.com/Staegrin/d39af449461189fbd7b219b1c4d037e3

![2017-11-11_18 15 02](https://user-images.githubusercontent.com/8494635/32691731-6b8eab16-c70c-11e7-8bb8-420000b2aaf2.png)
mekanism + modular machinery = no problem
![2017-11-11_18 15 57](https://user-images.githubusercontent.com/8494635/32691732-6da024d4-c70c-11e7-89e6-fb3a9725de3c.png)
modular machinery + limelib = no problem

**Comment by KidsDontPlay** [comment]
I guess it is not my fault.
@HellFirePvP
you should not [call](https://github.com/HellFirePvP/ModularMachinery/blob/master/src/main/java/hellfirepvp/modularmachinery/common/tiles/base/TileFluidTank.java#L89) default instance from unknown capabilites. not every one does support that. or put it in try-catch.

**Comment by HellFirePvP** [comment]
Sorry, the whole mekanism integration was past-midnight code :P 
i'll look into it for the next update.
