### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Nexusdog** [KidsDontPlay/LimeLib#17]
MC/F 1.12.2/2606

Tried connecting a fluid transfer node to tinkers furnace, specifically the glass tank & game froze up. I checked over the crash report... I'm not very good at it, but I did see Limelib mentioned a lot = apologies if this isn't relevant.

Crash log

https://pastebin.com/wYiN37jW

**Comment by KidsDontPlay** [comment]
the bug is known
https://github.com/rwtema/extrautilities/issues/1857

you can use the previous version of ExU
