### ISSUE TITLE
crash on load even when i diabled the hud options in config(1.12.2)

### ISSUE THREAD

**Issue by SDUBZ** [KidsDontPlay/LimeLib#18]
forge: 1.12.2-2608
limelib: limelib-1.12.2-1.7.9
exu2: extrautils2-1.12-1.7.3

crash:
[crash-2018-02-02_14.52.50-server.txt](https://github.com/MrRiegel/LimeLib/files/1688009/crash-2018-02-02_14.52.50-server.txt)

**Comment by KidsDontPlay** [comment]
duplicate #17
