### ISSUE TITLE
RandomShapedRecipe doesn't seem like a good idea.

### ISSUE THREAD

**Issue by CptSpaceToaster** [KidsDontPlay/LimeLib#19]
https://github.com/MrRiegel/LimeLib/blob/da8e6eea222a6731140b8aa2267d4ddf1784cbcc/src/main/java/mrriegel/limelib/LimeLib.java#L79

https://github.com/MrRiegel/LimeLib/blob/3a15e5ff64804e99de9edf0174d4a2c6bc46ac43/src/main/java/mrriegel/limelib/util/Serious.java

Interferes with systems that consume available recipes, and doesn't seem to be easily configurable.  You might be losing users who would otherwise appreciate your mod.

https://www.reddit.com/r/feedthebeast/comments/83lyad/what_mod_is_adding_this_recipe/

**Comment by KidsDontPlay** [comment]
Damnit, you got me. ;)
I'm gonna remove the recipe.
