### ISSUE TITLE
LimeLib Forge Energy crash

### ISSUE THREAD

**Issue by kd8lvt** [KidsDontPlay/LimeLib#20]
This error occurs with and without the Redstone Flux API. I also have Furnus installed. 
Error occurs on item pickup (picking up any item causes the error) and the error persists after re-joining world.
[Crash Report](https://pastebin.com/eewFxtZ4)

**Comment by KidsDontPlay** [comment]
check the blocks around you. It seems that one block doesn't handle the energy capability correctly.

**Comment by kd8lvt** [comment]
It was a brand-new world, I had just picked up some raw mutton and it crashed. I don't think any block would be causing the issue in a brand-new world, not to mention I don't have any other FE-using mods installed, as far as I know.
    It could also be world-gen, but again, I'm pretty sure there's no other mods that hook into FE, and I doubt you're doing anything with world-gen.
    It's a Vanilla+ pack, so I'm pretty sure there aren't any extra ores, etc. Either way, I'll look into it some more.

I was in a mesa, next to some grass and trees, so Hardened Clay, Dirt, Wood, Leaves, (Tall) Grass, Wolves, Sheep; and possibly a mineshaft structure underground, so; Planks, (Minecart) Chests, Fences,  Rails, etc

The loot for a chest isn't generated until the chest is opened, so it wouldn't be anything inside the chests. I really don't know though...

**Comment by KidsDontPlay** [comment]
can you try this one. ~https://drive.google.com/open?id=1c7ahHfNxqNQcgWK3_2d8YX0_lHV4W7dT~ https://drive.google.com/open?id=1arhXzpMZKZ2iqDoc_hXe82PlAfektZju
I am sure it will crash too but gives more information

**Comment by kd8lvt** [comment]
Sorry about the delay, my power cut out from an ice storm, (hurrah northern altitudes), and I've been having issues with my computer since. Here's the log. Looks like it's the vanilla furnace! Here's the [new log](https://pastebin.com/wF7nPpxF) Though, I'm not sure where a vanilla furnace would be in that mesa, I have Recurrent Complex installed, so it might be a worldgen that loaded and I just didn't see it.

**Comment by KidsDontPlay** [comment]
did you use the first link? if so, use the second instead

**Comment by kd8lvt** [comment]
Nope, I used the second link, if my memory serves. (Though I possibly mis-clicked) I will try (re)downloading from the second link tomorrow, as it is a bit late here, and I've got work in the morning. I'll comment again tomorrow with the results

**Comment by KidsDontPlay** [comment]
better use [this](http://www.mediafire.com/file/l4opbimdcp2ewz8/limelib-1.12.2-1.7.10-test-3.jar). it shows the position of the tile entity.

**Comment by kd8lvt** [comment]
[New crashlog](https://pastebin.com/Hx9LuzKb)
Checked the coords in the log with LimeLib disabled, it is a furnace within my base, so it's not some weirdness with incorrect TileEntity-Block pairs.

**Comment by KidsDontPlay** [comment]
I have absolutely no idea how this can happen. It's a vanilla block and it wasn't modified (afaik).
Is that a modpack I can download to test it on my own?

**Comment by kd8lvt** [comment]
[Vanilla+ Kd Edition-1.0.zip](https://github.com/MrRiegel/LimeLib/files/1926159/Vanilla.Kd.Edition-1.0.zip)
Here's the Twitch App instance. I used to have foamfix but before I started this issue I tested without (and kept it disabled) so it's not that. I've even tried on new worlds, same issue.

**Comment by KidsDontPlay** [comment]
your forge version is buggy. try updating it
