### ISSUE TITLE
Game Crash with World Corruption

### ISSUE THREAD

**Issue by remclave** [KidsDontPlay/LimeLib#22]
LimeLib Version: 1.7.12
Forge Version: 2760

In relation with:
NuclearCraft version: 2.12

https://paste.dimdev.org/cariqenuyu.mccrash

Per the above crash report, I'm posting here.

Just place the block in world. 
World crash. 
Cannot reconnect to saved world.
Load new World. 
Rinse and repeat.

This is a repeatable crash with all three versions of the NuclearCraft Infinite Water Source block.

**Comment by KidsDontPlay** [comment]
@turbodiesel4598
Why do you do this [try-catch](https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/util/GasHelper.java#L45-L49) only if gregtech is installed?
Or use the capability name.
```java
String name = capability.getName();
return name.equals("mekanism.api.gas.IGasHandler") || name.equals("mekanism.api.gas.ITubeConnection");
```

**Comment by tomdodd4598** [comment]
Good question - I must have forgotten to generalise it after testing where that sort of UnsupportedOperationException crash was coming from - will get fixed now!
Unfortunately the Mek capabilities are not in the API so it's a bit tricky to get to them :P

**Comment by remclave** [comment]
Thank you both for your quick work. I look forward to the updates later.
