### ISSUE TITLE
limelib(1.11.2) help needed for compat reading of block(causing game lock up)

### ISSUE THREAD

**Issue by SDUBZ** [KidsDontPlay/LimeLib#3]
limelib: limelib-1.11.2-1.4.1
Forge: 1.11.2-2253
hammer core: HammerCore_1.11.2-1.2.9
blackhole storage: Black Hole Storage 1.11.2-4b
fml client latest:
[fml-client-latest (2).txt](https://github.com/MrRiegel/LimeLib/files/819811/fml-client-latest.2.txt)

**Comment by KidsDontPlay** [comment]
that's a problem with black hole storage.
it's up to @MrDimkasStudio
[crash](https://hastebin.com/tapojozeta.vbs)

**Comment by SDUBZ** [comment]
okay i will let him know :D
