### ISSUE TITLE
SP crash / MP disconnect when using Voidcraft Macerator

### ISSUE THREAD

**Issue by davqvist** [KidsDontPlay/LimeLib#6]
MC ~1.10.2~ 1.12
Forge 2420
LimeLib 1.7.4

SP Crash Log; https://pastebin.com/4BF2WicN
Happens to everybody going near a Macerator from Voidcraft.
I tried to turn of the Energy Overlay in MP which maybe caused it, but it didn't fix it.
Let me know if you need more info or if I should report to Voidcraft dev.

**Comment by KidsDontPlay** [comment]
not my fault.
@Tamaized

**Comment by davqvist** [comment]
Oops sorry about MC 1.10.2, it's hard to get rid of old habits, will report to dev.

**Comment by Tamaized** [comment]
~~This was fixed in the 1.12 branch long ago, unfortunately I've dropped support for 1.10.~~

Edit: okay I shouldn't respond right when waking up >.>
