### ISSUE TITLE
[Issue] 1.12 Omegacraft

### ISSUE THREAD

**Issue by accessdenied0** [KidsDontPlay/LimeLib#8]
Hello Mr. Riegel,

[I recently run into a issue, while I was using the RF-Inverter from Omegacraft. ](https://pastebin.com/j60GP1h9)
Now I'm not sure if this issue is on your end, but because of multiply reasons I was hoping to get maybe some help here. 
If this doesn't concern you at all I apologize to bother you in advance.

Thank you for your help.

**Comment by KidsDontPlay** [comment]
it's omegacrafts's fault

**Comment by accessdenied0** [comment]
Thank you for your help. I do link him this issue. I'm sorry for bothering you.
