### ISSUE TITLE
Flux Inverter incompatability

### ISSUE THREAD

**Issue by Cobbs3** [KidsDontPlay/LimeLib#9]
The recent issue #8 brought this up and the guy went to me with the crash report after some inspection of the area I noticed that the error is not my fault here is the method in question.

@Override
    public boolean hasCapability(Capability<?> capability, EnumFacing facing) {
        if(capability.equals(CapabilityEnergy.ENERGY)){
            if(facing.equals(EnumFacing.UP)){
                return true;
            }
        }
}

The line that errors is  if(facing.equals(EnumFacing.UP)){
which means you are giving a null into the method instead of an EnumFacing which is not correct.
I can stop it crashing on my end by flipping the values around but you shouldn't be giving that method a null direction.

**Comment by KidsDontPlay** [comment]
You are wrong.
enumfacing can be null.
`boolean hasCapability(@Nonnull Capability<?> capability, @Nullable EnumFacing facing);`
read the javadocs for `ICapabilityProvider`

**Comment by Cobbs3** [comment]
Fair enough, sorry about that I probably should have checked but it did seem like an odd thing to end up with.
